# Model arguments
model_name_or_path: meta-llama/Meta-Llama-3.1-8B
stduent_model_path: nvidia/Llama-3.1-Minitron-4B-Depth-Base
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
chat_template: "{% for message in messages %}\n{% if message['role'] == 'user' %}\n{{ '<|user|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'system' %}\n{{ '<|system|>\n' + message['content'] + eos_token }}\n{% elif message['role'] == 'assistant' %}\n{{ '<|assistant|>\n'  + message['content'] + eos_token }}\n{% endif %}\n{% if loop.last and add_generation_prompt %}\n{{ '<|assistant|>' }}\n{% endif %}\n{% endfor %}"
dataset_mixer:
  JunxiongWang/sftdataset: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 64

# SFT trainer config
bf16: true
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 8
gradient_checkpointing: false
gradient_checkpointing_kwargs:
  use_reentrant: False
learning_rate: 2.0e-05
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 8192
pre_filter_max_seq_length: 7000
max_steps: -1
num_train_epochs: 1
output_dir: /data/junxiong/prompt_distill/distill_student_teacher_depth/
overwrite_output_dir: true
per_device_eval_batch_size: 1  # change to 8?
per_device_train_batch_size: 1  # chage to 8?
push_to_hub: false
remove_unused_columns: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 10000
save_total_limit: 1
seed: 42
warmup_ratio: 0.01
embedding_transform_strategy: select_layer_all
embeddings_from_layer_n: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 31